-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 14 May 2024, 21:19:26
-- Sunucu sürümü: 10.4.32-MariaDB
-- PHP Sürümü: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `yemektarifiotomasyonu`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `kullanici`
--

CREATE TABLE `kullanici` (
  `Id` int(11) NOT NULL,
  `Eposta` varchar(255) NOT NULL,
  `AdiSoyadi` varchar(255) NOT NULL,
  `Sifre` varchar(255) NOT NULL,
  `Admin` int(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Tablo döküm verisi `kullanici`
--

INSERT INTO `kullanici` (`Id`, `Eposta`, `AdiSoyadi`, `Sifre`, `Admin`) VALUES
(1, 'metehan@gmail.com', 'Metehan Akbulut', '909cdpb2dcap87arcmab878l9d93abbg', 1),
(3, 'admin', 'admin ', '909cdpb2dcap87arcmab878l9d93abbg', 1),
(4, 'user', 'user', 'c1escreraiegade2809mereo9h9uegal', 0);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `yemektarifi`
--

CREATE TABLE `yemektarifi` (
  `Id` int(11) NOT NULL,
  `Baslik` varchar(255) NOT NULL,
  `Aciklama` text NOT NULL,
  `ResimUrl` varchar(255) NOT NULL,
  `KullaniciId` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Tablo döküm verisi `yemektarifi`
--

INSERT INTO `yemektarifi` (`Id`, `Baslik`, `Aciklama`, `ResimUrl`, `KullaniciId`) VALUES
(15, 'Şehriyeli Tavuk Suyu Çorbası ', 'Şehriyeli Tavuk Suyu Çorbası İçin Malzemeler\r\n\r\n•	200 gr tavuk göğsü\r\n•	1 tk tuz (haşlarken kullanılacak)\r\n•	1 su bardağı tavuk suyu\r\n•	3 su bardağı sıcak su\r\n•	Yarım çay bardağı tel şehriye\r\n•	1 tk tuz, 1 tk nane, 1 çk pulbiber, 1 çk karabiber\r\nTerbiyesi için;\r\n•	2 yk un\r\n•	1 yk limon suyu\r\n•	2 su bardağı ılık su\r\n\r\nŞehriyeli Tavuk Suyu Çorbası Nasıl Yapılır?\r\n\r\n1.	Tavuk etini uygun bir tencereye alarak üzerine tuz ekleyelim.\r\n2.	Üzerini geçecek kadar su ilave ettikten sonra haşlanmaya bırakalım, haşlanırken ara ara üzerinde oluşan köpükleri temizleyelim.\r\n3.	Tavuğumuz haşlandıktan sonra suyun içerisinden alalım ve tavuk suyunu da bir süzgeçten geçirerek bir kenara alalım.\r\n4.	Tavuk göğsümüz soğuduktan sonra didikleyelim.\r\n5.	Çorba tenceresine tavuk suyunu, sıcak suyu ve didiklenmiş tavuk etlerini ekleyip kaynatalım.\r\n6.	Kaynadıktan sonra içerisine tel şehriyeleri ilave edip karıştıralım.\r\n7.	Terbiyesi için limon suyu, un ve suyu çırparak çorbaya ilave edelim. Çorbamızı kısık ateşte, ara ara karıştırarak pişmeye bırakalım.\r\n8.	Şehriyeler pişmeye yakın tuz, nane, isteğe bağlı pul biber ve karabiber serperek 5 dakika kadar kaynattıktan sonra ocaktan alalım.\r\n', 'https://s8k8w4m8.rocketcdn.me/wp-content/uploads/2021/02/tel-sehriyeli-tavuk-suyuna-corba-tarifi.jpg', 1),
(17, 'Ezogelin Çorbası', 'Ezogelin Çorbası İçin Malzemeler\r\n\r\n•	1 su bardağı kırmızı mercimek\r\n•	1 tk pirinç\r\n•	1 tk bulgur\r\n•	2 çk pul biber, 1 yk nane ve tuz\r\n•	2 diş sarımsak\r\n•	1 orta boy soğan\r\n•	1 yk biber salçası\r\n•	1 yk tereyağı\r\n•	2 litreye yakın sıcak su\r\n\r\nEzogelin Çorbası Nasıl Yapılır?\r\n\r\n1.	Ezogelin çorbası yapmak için düdüklü tencerede önce rendelemiş olduğumuz soğanı ve ezmiş olduğumuz sarımsağı tereyağında kavuruyoruz.\r\n2.	Soğanlar diriliğini kaybetsin yeterli yakmadan orta ateşte kavuralım.\r\n3.	Soğanlar kavrulunca naneyi, kırmızı biberi ve salçayı ilave edip. Kavurmaya devam edelim.\r\n4.	Bir iki karıştırdıktan sonra yıkadığımız mercimeği, pirinci, bulguru ve tuzunu da ilave ederek karıştıralım.\r\n5.	Başka bir tarafta kaynamakta olan 2 litreye yakın suyu üzerine boşaltalım.\r\n6.	Düdüklünün kapağını ve düdüğünü kapattıktan sonra 10 dakika pişiriyoruz\r\n', 'https://image.hurimg.com/i/hurriyet/75/750x422/629620854e3fe02c2424a34a.jpg', 1),
(18, 'Yayla Çorbası ', 'Yayla Çorbası İçin Malzemeler\r\n\r\n•	1 çay bardağı pirinç\r\n•	3 su bardağı su\r\n•	3 su bardağı sıcak su (tavuk suyu veya kemik suyu)\r\n•	Tuz\r\n\r\nTerbiyesi için:\r\n•	1 adet yumurta sarısı\r\n•	1,5 su bardağı yoğurt\r\n•	1 yk un\r\n\r\nSosu için:\r\n•	2 yk tereyağı\r\n•	1 yk kuru nane\r\n\r\nYayla Çorbası Nasıl Yapılır?\r\n\r\n1.	Yayla çorbası için ilk olarak pirinçler yıkanarak suda yumuşayıncaya kadar haşlanır.\r\n2.	Yayla çorbamızın terbiyesi için diğer taraftan yumurta sarısı, yoğurt, un bir kasede iyice çırpılır.\r\n3.	Pişen pirinçlere varsa et ya da kemik suyu yoksa 3 su bardağı sıcak su ilave edilir.\r\n4.	Çorbanın suyundan 1-2 kepçe alınarak yavaş yavaş alınıp terbiyeye ilave edilir.\r\n5.	Hafifçe sulanan bu karışım ılınmış olan çorbaya ilave edilir ve 1-2 taşım kaynatılır.\r\n6.	En son tuzu ilave edilir, bir kaç dakika daha kaynatılarak ocak kapatılır.\r\n7.	Üzerine sos için kuru nane eritilmiş tereyağında kızdırılarak gezdirilir. \r\n', 'https://m.media-amazon.com/images/I/81T9e8e8wJL._AC_UF1000,1000_QL80_.jpg', 1),
(19, 'Kırmızı Mercimek Çorbası ', 'Kırmızı Mercimek Çorbası İçin Malzemeler\r\n\r\n•	2 su bardağı kırmızı mercimek\r\n•	1 adet soğan\r\n•	2 yk un\r\n•	1 adet havuç\r\n•	Yarım yk biber ya da  domates salçası \r\n•	Yarım çk karabiber, 1 çk kimyon, 1 tk kırmızı toz biber\r\n•	2 litre sıcak su\r\n•	5 yk sıvı yağ\r\n\r\nSosu için:\r\n•	2 yk tereyağı\r\n\r\nKırmızı Mercimek Çorbası Nasıl Yapılır?\r\n\r\n1.	Kırmızı mercimek çorbası için sıvı yağı tencereye alınarak yemeklik doğranan soğanlar hafif pembeleşinceye kadar kavrulur.\r\n2.	Daha sonra un ilave edilerek kısık ateşte kavurmaya devam edilir.\r\n3.	Salça kullanılacak ise salça ilave edilir, kavrulduktan sonra küp küp doğranmış havuç ve iyice yıkanıp suyu süzülen mercimekler ilave edilir.\r\n4.	Üzerine su eklenerek karıştırılır ve tencerenin kapağı kapatılır. Çorbamız kaynayana kadar orta ateşte, kaynadıktan sonra mercimekler ve havuçlar yumuşayana kadar ara ara karıştırılarak kısık ateşte pişirilir.\r\n5.	Çorba piştikten sonra el blenderı ile güzelce ezilir. Eğer blenderiniz yoksa süzgeçten de geçirebilirsiniz.\r\n6.	Karabiber, tuz ve isteğe bağlı olarak kimyon eklenir ve karıştırılır. 5 dakika daha pişirilerek ocaktan alınır.\r\n7.	Kıvamı koyu gelirse size, bir miktar su ilave edilerek bir taşım kaynatılır.\r\n8.	Bu arada küçük bir tavaya iki yk tereyağı alınır, kızdırılır ve bir tk kırmızı toz biber eklenerek ocaktan alınır.\r\n9.	Mercimek çorbası servis kasesine alındıktan sonra üzerine kırmızı biberli sos gezdirilir ve bir dilim limon ile servis edilir.\r\n', 'https://image.hurimg.com/i/hurriyet/75/750x422/60e4662a4e3fe0195427e88c.jpg', 1),
(20, 'Yoğurt Çorbası ', 'Yoğurt Çorbası İçin Malzemeler\r\n\r\n•	1 su bardağı yoğurt\r\n•	3 tepeleme yk un\r\n•	5 su bardağı su\r\n•	1 çay bardağı erişte\r\n•	1 tk tuz\r\n\r\nSosu için;\r\n•	1 yk tereyağı\r\n•	1 tk kırmızı toz biber, 1 tk nane\r\n\r\nYoğurt Çorbası Nasıl Yapılır?\r\n\r\n1.	Öncelikle tenceremize yoğurt, un ve suyu ilave ederek tel çırpıcı yardımı ile pürüzsüz bir kıvam alana kadar çırpalım.\r\n2.	Tenceremizi ocağa alalım ve kaynayana kadar orta ateşte karıştırarak pişirelim.\r\n3.	Çorbamız kaynadıktan sonra erişteyi ekleyelim ve kısık ateşte ara ara karıştırarak şehriyeler yumuşayıncaya kadar pişirelim.\r\n4.	Tuzumuzu da ekleyelim ve 1-2 dakika daha kaynatarak ocağı kapatalım. Çorbamızı 10 dakika kadar dinlenmeye bırakalım.\r\n5.	Sosu için uygun bir sos tavasına tereyağını alalım ve eritelim.\r\n6.	Üzerine pul biber ve naneyi ekleyerek kızdıralım ve ocaktan alalım. Bu aşamada ocağı yüksek ateşte açmamaya dikkat edelim.\r\n7.	Çorbamızı kaselere alalım ve üzerine sostan gezdirerek servis edelim. Dilerseniz sosu tencereye aktarıp o şekilde de servis edebilirsiniz.\r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2019/05/pirincli-yogurt-corbasi-yeni.jpg', 1),
(21, 'Mantar Çorbası', 'Mantar Çorbası İçin Malzemeler\r\n\r\n•	2 adet kuru soğan\r\n•	10 adet mantar\r\n•	4 yk sıvı yağ\r\n•	1 yk tereyağı\r\n•	2 yk un\r\n•	1 litre sıcak su\r\n•	1 su bardağı süt\r\n•	Yarım çk karabiber, 1 tk tuz\r\n\r\nSosu için;\r\n\r\n•	1 yk tereyağı\r\n•	1 tk kırmızı toz biber\r\n\r\nMantar Çorbası Nasıl Yapılır?\r\n\r\n1.	Öncelikle soğanları ince ince doğrayalım.\r\n2.	Ardından mantarları minik minik doğrayalım. Bu aşamada dilerseniz mantarlarınızı yıkayabilir, dilerseniz de silebilirsiniz.\r\n3.	Tencereye sıvı yağ ve tereyağını alarak erimesi için bekleyelim.\r\n4.	Eridikten sonra soğanları ekleyelim ve hafif pembeleşene kadar kavuralım.\r\n5.	Mantarları da ekleyelim ve orta ateşte mantarlar suyunu salıp çekinceye kadar kavuralım.\r\n6.	Daha sonra unu ilave edelim ve unun kokusu çıkana kadar kavuralım.\r\n7.	Bir taraftan karıştırırken bir taraftan da suyumuzu ekleyelim ve orta ateşte çorbamızı kaynamaya bırakalım.\r\n8.	Çorbamız kaynadıktan sonra altını kısalım ve oda ısısındaki sütü ve karabiberi ilave ederek karıştıralım ve kaynamaya bırakalım.\r\n9.	Son kez tuzumuzu da ekleyelim ve karıştırarak çorbamızı ocaktan alalım.\r\n10.	Çorbamızın sosu için tavaya tereyağını alalım ve eritelim.\r\n11.	Eriyen tereyağına kırmızı toz biberi ekleyerek kızdıralım ve ocaktan alalım.\r\n12.	Çorbamızı kaselere koyduktan sonra üzerine sosumuzdan gezdirelim. Dilerseniz sosu tencereye aktarabilir ve karıştırarak servis edebilirsiniz.\r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2020/10/sutlu-mantar-corbasi-asligul.jpg', 1),
(22, 'Sütlü Domates Çorbası', 'Sütlü Domates Çorbası İçin Malzemeler\r\n\r\n•	2 yk sıvı yağ\r\n•	1 yk tereyağı\r\n•	2 tepeleme yk un\r\n•	1 yk domates salçası\r\n•	5 adet domates\r\n•	4 su bardağı su\r\n•	Yarım su bardağı süt\r\n•	1 tk tuz\r\n\r\nSütlü Domates Çorbası Nasıl Yapılır?\r\n\r\n1.	Öncelikle domatesler rendelenir. Ardından tereyağı ve sıvı yağ tencereye alınır, tereyağı eritilir.\r\n2.	Tereyağı eridikten sonra un eklenerek biraz kavrulur.\r\n3.	Unun kokusu çıktıktan sonra domates salçası eklenir ve biraz karıştırılarak kavrulur\r\n4.	Rendelenmiş domatesler eklenir. 3-4 dakika daha kavrulur.\r\n5.	4 su bardağı su eklenerek çırpılır, kısık ateşte pişmeye bırakılır. Dilerseniz bu aşamada veya servisten önce çorbayı blenderdan geçirerek pürüzsüz bir kıvam almasını sağlayabilirsiniz.\r\n6.	Tuz ve süt eklenerek karıştırılır. Tuz miktarını kendi damak zevkinize göre ayarlayabilirsiniz.\r\n7.	Hazır olan çorba ocaktan alınarak kaselere paylaştırılır. İsteğe göre üzerine kaşar peyniri rendesi ve karabiber serpilir.\r\n8.	Nefis Sütlü domates çorbası tarifimiz servise hazır. Dilerseniz üzerine krema gezdirerek servis edebilirsiniz. \r\n', 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/701eb829-c4ab-4c1f-8a39-9ebc0a1dfdd9/Derivates/6676c224-1638-4580-ac01-7e2d481cb6a8.jpg', 1),
(23, 'Karnıyarık', 'Karnıyarık Yemeği İçin Malzemeler\r\n\r\n•	6 adet küçük boy patlıcan \r\n•	3 adet sivri biber\r\n\r\nKıymalı Harç İçin;\r\n\r\n•	2 adet orta boy soğan\r\n•	2 adet domates\r\n•	2 adet sivri biber\r\n•	2 diş sarımsak\r\n•	Sıvı yağ, tuz, karabiber, kırmızıbiber\r\n•	200 gr kıyma\r\n•	1 çay bardağı sıcak su\r\n\r\nSosu İçin;\r\n\r\n•	1 yk salça\r\n•	1 su bardağı sıcak su\r\n\r\nKarnıyarık Yemeği Nasıl Yapılır?\r\n\r\n1.	Patlıcanları çizgili soyup, yarım saat yağ çekmemesi için tuzlu suda bekletin.\r\n2.	İyice yıkadıktan sonra suyunu havlu ile çektirin ve az yağda kızartın. 3 adet biberi de yağda kızartın.\r\n3.	Daha sonra aynı tavada doğranmış soğanları kavurun, kıymayı ekleyerek bir müddet daha kavurun ve biberleri, sarımsağı ekleyerek 2 dakika daha kavurun.\r\n4.	Küp küp doğramış olduğunuz 2 adet domatesi, tuzu, baharatları ekleyerek karıştırın.\r\n5.	Üzerine bir çay bardağı su ekleyerek 5 dk kaynatın.\r\n6.	Tepsiye patlıcanların ortalarını keserek yerleştirin ve bu kesiklerden patlıcanın içine bastırarak iç malzemesine yer açın ve malzeme ile patlıcanları doldurun.\r\n7.	Doldurduğunuz patlıcanların üzerine ortadan ikiye kestiğiniz çeri domatesi ya da 1 adet domatesi eşit büyüklükte olacak şekilde paylaştırın ve kızarttığımız biberlerden birer tane koyun.\r\n8.	Ayrı bir yerde 1 kaşık salçayı, 1 su bardağı sıcak suda ezerek patlıcanların aralarına dökün. Kıymalar çıkmasın diye üzerine dökmeyin.\r\n9.	Daha sonra 170 derece de ısıttığınız fırına sürerek 20-25 dk pişirin.\r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2022/08/100-gram-kiymayla-karniyarik-one-cikan.jpg', 1),
(24, 'Et Sote', 'Et Sote Yemeği İçin Malzemeler\r\n\r\n•	5 yk sıvı yağ\r\n•	1 yk tereyağı\r\n•	1 adet soğan\r\n•	500g kuşbaşı et\r\n•	2 adet domates\r\n•	4 adet sivri biber\r\n•	Pul biber, karabiber, kekik, tuz\r\n•	Sıcak su (üzerini geçecek kadar)\r\n\r\nEt Sote Yemeği Nasıl Yapılır?\r\n\r\n1.	Tavaya sıvı yağ ve tereyağını alalım.\r\n2.	 Tereyağı eridikten sonra doğranmış soğanı ekleyerek kavuralım.\r\n3.	 Kuşbaşı doğranmış eti de ilave edelim.\r\n4.	 Tencerenin kapağını kapatalım ve ara ara karıştırarak etler suyunu salıp çekinceye kadar pişirelim.\r\n5.	 Doğranmış domates ve doğranmış sivribiberi ilave edelim.\r\n6.	 Tencerenin kapağını kapatıp domatesler suyunu salıncaya kadar pişirmeye devam edelim.\r\n7.	 Daha sonra pul biber, karabiber ve kekiği ekleyerek karıştıralım.\r\n8.	 Etlerin üzerini geçecek şekilde sıcak suyu ilave edip karıştıralım ve tencerenin kapağını tekrar kapatalım.\r\n9.	 Etimiz lokum gibi yumuşayıncaya kadar pişirelim.\r\n10.	 Son olarak tuzunu ayarlayıp karıştıralım.\r\n11.	 5 dk daha pişirdikten sonra ocağı kapatalım. \r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2023/01/lokanta-usulu-et-sote-sunum-yemekcom.jpg', 1),
(25, 'Etli Nohut', 'Etli Nohut İçin Malzemeler\r\n\r\n•	Yarım kilo kuşbaşı doğranmış et\r\n•	1,5 su bardağı haşlanmış nohut\r\n•	1 adet kuru soğan\r\n•	3 yk sıvı yağ\r\n•	2 yk salça\r\n•	Tuz, pul biber\r\n\r\nEtli Nohut Nasıl Yapılır?\r\n\r\n1.	Eti kuşbaşı doğrayarak yumuşayana kadar haşlayın.\r\n2.	Soğanları yemeklik doğrayarak sıvı yağda pembeleşene kadar kavurun.\r\n3.	Salçayı, tuzunu, pul biberini ilave edip 2 dakika daha kavurun.\r\n4.	Haşlanmış etleri ve haşlanmış nohutu da ilave ederek bir kaç kez karıştırın.\r\n5.	Daha sonra üzerlerine çıkacak kadar yaklaşık 6 su bardağı kaynamış su koyup beraber 10-15 dakika kadar kaynattıktan sonra ocağı kapatabilirsiniz.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2018/05/etli-nohut-tarifi-one-cikan.jpg', 1),
(26, 'Tavuk Sote ', 'Tavuk Sote İçin Malzemeler\r\n\r\n•	Yarım kg tavuk göğsü\r\n•	2 yk sıvı yağ\r\n•	1 tk domates salçası\r\n•	2 adet yeşil biber\r\n•	1 adet kırmızı biber\r\n•	1 adet soğan\r\n•	2 diş sarımsak\r\n•	2 adet domates\r\n•	Karabiber, pul biber, tuz\r\n•	1 su bardağı su\r\n\r\nTavuk Sote Nasıl Yapılır?\r\n\r\n1.	Tavuk etini kuşbaşı doğrayın.\r\n2.	Soğanları yemeklik, biberleri julyen doğrayın, domatesleri de küp küp doğrayın.\r\n3.	Kısık ateşte tavukları arada karıştırarak kavurun.\r\n4.	Suyunu biraz çektikten sonra soğanları ve ince kesilmiş sarımsağı ekleyin.\r\n5.	1-2 dk kavurduktan sonra biberleri ilave edin.\r\n6.	Biberler de sotelenince domatesi, salçayı, baharatları ve tuzu ekleyip pişirmeye devam edin.\r\n7.	Son olarak 1 bardak suyu ekleyin ve etler pişene kadar kapağı kapalı bir şekilde pişirin.\r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2015/08/tavuk-sote-yemekcom.jpg', 1),
(27, 'Patatesli Sulu Köfte ', 'Patatesli Sulu Köfte Yemeği İçin Malzemeler\r\n\r\n•	200 g kıyma\r\n•	3 adet orta boy patates\r\n•	1 adet soğan\r\n•	2 yk kısırlık bulgur\r\n•	2 yk domates salçası\r\n•	2 yk sıvı yağ\r\n•	2 yk kadar un\r\n•	2-3 diş ezilmiş sarımsak\r\n•	Kırmızı biber\r\n•	Karabiber, pul biber, tuz\r\n\r\nPatatesli Sulu Köfte Yemeği Nasıl Yapılır?\r\n\r\n1.	İlk olarak yemeğimizin köftelerini hazırlayalım. Kıymanın üzerine bulgur, sarımsak, baharatlar ve biraz da tuz ekleyerek iyice yoğuralım. Vaktiniz varsa üzerini streçleyerek 15 dakika kadar buzdolabında bekletebilirsiniz.\r\n2.	Ufak ufak yuvarladığımız köfteleri içerisine un serptiğimiz kaba alarak una bulanmalarını sağlayalım.\r\n3.	Soğanları doğrayalım ve sıvı yağda soğanlar pembeleşinceye kadar kavuralım.\r\n4.	Domates salçasını ilave ederek kavuralım.\r\n5.	Küp küp doğramış olduğunuz patatesi ilave ederek 1-2 dakika kadar daha kavuralım.\r\n6.	Patateslerin üzerini 2 parmak geçecek kadar sıcak su ilave edelim.\r\n7.	Yemek kaynadıktan sonra köfteleri ilave ederek, tuz ve baharatını ilave edelim.\r\n8.	Su miktarını kontrol ederek yemeğimizi kaynadıktan sonra kısık ateşte pişmeye bırakalım. (Yemek pişene kadar zaman zaman suyunu kontrol ederek gerekirse ekleyelim.)\r\n', 'https://i.ytimg.com/vi/zrlrz_bQcIQ/maxresdefault.jpg', 1),
(28, 'Fırında Hamsi ', 'Fırında Hamsi İçin Malzemeler\r\n\r\n•	1 kg hamsi\r\n•	Yarım su bardağı mısır unu\r\n•	1 silme tk tuz\r\n\r\nÜzeri için;\r\n\r\n•	Sıvı yağ\r\n\r\nFırında Hamsi Nasıl Yapılır?\r\n\r\n1.	Mısır ununu bir tabağın içerisine alalım. Eğer buğday unu da kullanacaksanız mısır unu ve normal unu bir kapta karıştırmalısınız.\r\n2.	Ayıklanmış suyu süzülmüş ve tuzlanmış hamsileri una bulayarak yağlı kağıda diziyoruz. Dilerseniz hamsileri tuzlamadan tuzu mısır ununun içerisine de karıştırabilirsiniz.  Balıklarınızı yıkadıktan sonra süzgeç içerisinde bekleterek suyunun süzülmesini sağlayabilirsiniz.\r\n3.	Balıklar rahat çıksın diye kağıdın üzerine de az yağ sürebilirsiniz ancak buna çok fazla gerek olmayacaktır. Balıklarımızı tepsimize aralarında boşluk kalmayacak şekilde dizelim.\r\n4.	Dizme işleminden sonra fırça ile balıkların üzerine de biraz yağ sürün. Eğer fırça kullanmak istemezseniz elinizle de gezdirebilirsiniz. Bu işlem balıklarınızın daha çıtır olmasını sağlayacaktır. Dilerseniz tepsinize 3-4 adet defne yaprağı da yerleştirebilirsiniz.\r\n5.	Ve balıklar fırına girmeye hazır. Önceden ısıttığınız 180°C fırında yaklaşık 30-35 dakika kadar kontrollü bir şekilde pişirelim.\r\n', 'https://cdn.ye-mek.net/App_UI/Img/out/650/2022/09/firinda-hamsi-resimli-yemek-tarifi(11).jpg', 1),
(29, 'Ali Nazik Kebabı ', 'Ali Nazik Kebabı İçin Malzemeler\r\n\r\n•	400 gram süzme yoğurt\r\n•	3-4 adet kemer patlıcan\r\n•	Tuz\r\n•	2-3 diş sarımsak\r\n\r\nDiğer Malzemeler;\r\n\r\n•	500 gram dana kuşbaşı\r\n•	1 yk tereyağı\r\n•	Tuz, karabiber, pul biber, kekik\r\n•	Yarım su bardağı su\r\n•	2 yk domates sosu\r\n\r\nAli Nazik Kebabı Nasıl Yapılır?\r\n\r\n1.	Patlıcanları közleyip, kabuklarını temizleyin.\r\n2.	İnce ince doğrayın.\r\n3.	Soğuduktan sonra, ezilmiş sarımsak ve süzme yoğurtla beraber iyice karıştırın.\r\n4.	Tuzunu ayarlayın.\r\n5.	Diğer taraftan etleri yıkayıp, suyunu süzdürün.\r\n6.	Pişirme kabına alarak kısık ateşte, tencerenin kapağı kapalı bir şekilde etlerin bırakmış olduğu suyu çekmesini bekleyin.\r\n7.	Daha sonra tereyağını ilave edin.\r\n8.	Tuz hariç, baharatları ve domates sosunu ilave edin.\r\n9.	Mutlaka sıcak su ekleyin. Çok sulu olmayacak, sadece koyu kıvamlı bir sosumuz olacak.\r\n10.	Etlerin pişme süresi uzarsa, sık sık kontrol edip gerekirse tencerenin dibi tutmaması için az az sıcak su ilave edebilirsiniz.\r\n11.	Pişen etlere, son olarak tuzu ilave edin ve ocaktan alın.\r\n12.	Servis tabağına önce patlıcanlı harç, üzerine ise etleri koyun.\r\n13.	İsteğe göre süsleyerek, servis edebilirsiniz.\r\n', 'https://cdn.yemek.com/mncrop/940/625/uploads/2017/05/alinazik-tarifi.jpg', 1),
(30, 'Ciğer Sote ', 'Ciğer Sote İçin Malzemeler\r\n\r\n•	1 kg dana ciğeri \r\n•	2 adet soğan\r\n•	2 yk domates salçası\r\n•	Sıvı yağ\r\n•	Tuz, pul biber\r\n•	1 su bardağı sıcak su\r\n\r\nCiğer Sote Nasıl Yapılır?\r\n\r\n1.	Ciğerlerin zarı soyularak iri küpler halinde doğrayalım. Biraz süzgeçte bekletelim ve varsa kanın süzülmesini sağlayalım. (Ciğerimizin yumuşak olması için dikkat etmemiz gereken püf noktaları tarifin devamında bulabilirsiniz)\r\n2.	Ciğerlerimizi tencereye alarak suyunu verip çekene kadar pişirelim. Bu aşamada tencerenin kapağını kapalı tutalım ve orta ateşte pişirelim.\r\n3.	Suyunu çekince  3-4 yk sıvı yağ ilave edilip daha önceden yemeklik doğranmış soğanları ekleyelim.\r\n4.	Soğanlar diriliğini yitirinceye kadar kavurmaya devam edelim.\r\n5.	Daha sonra salça ve baharatları ekleyerek ciğer sotemizi karıştıralım.\r\n6.	Bir su bardağı kadar da sıcak su ekleyelim kısık ateşte 8-10 dk daha pişirelim.\r\n', 'https://cdn.ye-mek.net/App_UI/Img/out/650/2023/07/ciger-sote-resimli-yemek-tarifi(12).jpg', 1),
(31, 'Şehriyeli Pirinç Pilavı ', 'Şehriyeli Pirinç Pilavı İçin Malzemeler\r\n\r\n•	2 yk tereyağı\r\n•	3 yk sıvı yağ\r\n•	2 su bardağı pirinç\r\n•	Yarım su bardağı arpa şehriye\r\n•	3 su bardağı tavuk suyu\r\n•	Tuz\r\n\r\nŞehriyeli Pirinç Pilavı Nasıl Yapılır?\r\n\r\n1.	Pirinçler bol su ile yıkanarak, ılık tuzlu suda yarım saat kadar bekletilir.\r\n2.	Bu süre sonunda, tuzlu suyu akıtılır ve pirinçler sudan geçirilerek, tüm suyu süzdürülür.\r\n3.	Pilav tenceresinde tereyağı eritilir, sıvı yağ da eklenerek üzerine arpa şehriyeler eklenir.\r\n4.	Şehriyenin rengi dönene kadar kavrulur.\r\n5.	Pirinçler ilave edilerek, 2-3 dk daha kavrulur.\r\n6.	Üzerine sıcak su eklenir ve tuzu ilave edilir.\r\n7.	Tencerenin kapağı kapatılarak, yüksek ateşte fazla suyu çekip pirinçler göz göz oluncaya kadar, yani pirinçlerin üzerinde su çekilip pirinçler göründüğünde kısık ateşe alın ve tamamen suyu çekene kadar pişirin. \r\n8.	Ocaktan aldıktan sonra, üzerine havlu kağıt koyarak kapağını tekrar kapatın ve demlenmesini bekleyin.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2018/10/arpa-sehriyeli-pirinc-pilavi-yemekcom.jpg', 1),
(32, 'Sebzeli Bulgur Pilavı ', 'Sebzeli Bulgur Pilavı İçin Malzemeler\r\n\r\n•	4 yk sıvı yağ\r\n•	1 adet soğan\r\n•	1 adet yeşil biber ve kırmızı biber\r\n•	1 adet patlıcan, 2 adet domates\r\n•	1 yk salça\r\n•	2 su bardağı bulgur\r\n•	1,5 tk tuz\r\n•	4 su bardağı sıcak su\r\n\r\nSebzeli Bulgur Pilavı Nasıl Yapılır?\r\n\r\n1.	Patlıcanları soyarak küçük küçük doğrayalım ve tuzlu suda 15-20 dk kadar bekletelim.\r\n2.	Soğanı yemeklik doğrayalım ve pembeleşene kadar sıvı yağda kavuralım.\r\n3.	Biberleri doğradıktan sonra tencereye ekleyelim ve soğanla birlikte kavurmaya başlayalım.\r\n4.	Patlıcanların suyunu süzelim, tencereye ekleyerek 3-4 dakika daha kavurmaya devam edelim.\r\n5.	Ardından küçük küçük doğranmış domatesleri ekleyelim ve karıştıralım.\r\n6.	Salçamızı da ekleyerek son kez karıştıralım ve tencerenin kapağını kapatarak orta ateşte, yaklaşık 3-4 dakika sebzeler pişene kadar bekleyelim.\r\n7.	Pişen sebzelerin üzerine yıkayıp suyunu süzdüğünüz bulgurları ekleyip karıştıralım.\r\n8.	Tuzu ve sıcak suyu da ilave ederek karıştıralım. Pilavın üzerini örtecek kadar su yeterli olacaktır.\r\n9.	Tencerenin kapağını kapatarak kaynayana kadar önce yüksek ateşte daha sonra kısık ateşte bulgurlar şişip yumuşayana kadar pişirelim.\r\n10.	Pilav suyunu çekip göz göz olduktan sonra ocağı kapatalım. Daha sonra kapağın altına kağıt havlu sererek 15 dakika kadar demlendirelim.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2021/05/bol-sebzeli-bulgur-pilavi-beste.jpg', 1),
(33, 'Pirinç Pilavı ', 'Pirinç Pilavı İçin Malzemeler\r\n\r\n•	2 su bardağı pirinç\r\n•	2,5 su bardağı sıcak su\r\n•	3 yk tereyağı\r\n•	1 yk sıvı yağ\r\n•	Tuz\r\n\r\nPirinçleri ıslatmak için;\r\n\r\n•	Pirinçlerin üzerini geçecek kadar ılık su\r\n•	Tuz\r\n\r\nPirinç Pilavı Nasıl Yapılır?\r\n\r\n1.	Pirinci bol su ile yıkayın. Uygun bir kaba alarak üzerini geçecek kadar ılık su ekleyin. Birazda tuz ilave edip karıştırın ve 15-20 dakika bekletin. Daha sonra yıkayarak suyunu süzün. \r\n2.	Tencerede tereyağını eritip suyu süzülmüş pirinci ekleyin ve 4-5 dakika kadar kavurun.\r\n3.	Pirinçler kavrulduktan sonra sıcak su veya sıcak et suyunu ekleyelim. İsterseniz yarım tavuk suyu yarım sıcak su kullanabilirsiniz. Son olarak tuzu ekleyin.\r\n4.	Pilavımızı kapağı kapalı bir şekilde önce yüksek ateşte pişmeye bırakalım.\r\n5.	Üzeri göz göz olduğunda yani üzerindeki suyu çekip pilavın üzerinde nokta nokta delikler oluştuğunda kısık ateşe alalım.  Pirinçler yumuşayıp suyu tamamen çekene kadar pişirelim.\r\n6.	Pişen pilavımızı ocaktan aldıktan sonra üzerine havlu peçete sererek kapağını tekrar kapatalım.\r\n7.	Pilavı 10-15 dk. dinlendirelim. \r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2023/10/airfryerda-pirinc-pilavi-yemekcom.jpg', 1),
(34, 'Perde Pilavı ', 'Perde Pilavı İçin Malzemeler\r\n\r\nİç pilavı için:\r\n\r\n•	3 su bardağı pirinç\r\n•	2 yk tereyağı\r\n•	4.5 su bardağı su ve tavuk suyu karışımı\r\n•	2 adet tavuk budu\r\n•	Yarım kahve fincanı kuş üzümü\r\n•	200 g çiğ badem\r\n•	1 kahve fincanı dolmalık fıstık\r\n•	Karabiber, tuz\r\n\r\nHamuru için:\r\n\r\n•	2 adet yumurta\r\n•	4 yk yoğurt\r\n•	Yarım su bardağı zeytinyağı\r\n•	Tuz\r\n•	Aldığı kadar un\r\n\r\nPerde Pilavı Nasıl Yapılır?\r\n\r\n1.	Tavuk butlarının haşlanması ile başladım. Tavukları haşladıktan sonra tavuk suyu ile pilavın yapımına başladım.\r\n2.	Tereyağını pilav tenceresinde eritin ve yıkayıp suyunu iyice süzdüğünün pirinçleri yağda 3-4 dakika kadar kavurun.\r\n3.	Haşladığımız tavukların suyundan 2 kasesini pirinçlerin üzerine ekleyin.\r\n4.	Yarım yk da tuz ekleyerek kapağını kapatın.\r\n5.	Pilav tam olarak pişmeden, hala diriyken ocaktan alın.\r\n6.	Didiklediğiniz tavukları, kuş üzümünü ve karabiberi pilav ile iyice harmanlayın.\r\n7.	Hamurun yapımı: tüm malzemeleri karıştırarak hamurunuzu yoğurun.\r\n8.	Hamuru biri küçük biri büyük iki parçaya ayırın.\r\n9.	Büyük olanı 3 mm kalınlığında açıp kabın tabanına, kenarları da kapatacak şekilde güzelce yerleştirin.\r\n10.	İçine pilavı boşaltın.\r\n11.	Hamurun küçük parçasını da aynı şekilde açıp pilavın üzerine kapatın.\r\n12.	200 derece ısıtılmış fırında perde pilavını kızarana kadar pişirin. Ters çevirip servis yapın.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2015/06/perde-pilavi-yemekcom.jpg', 1),
(35, 'Nohutlu Pilav ', 'Nohutlu Pilav İçin Malzemeler\r\n\r\n•	2 su bardağı pirinç\r\n•	3 su bardağı tavuk suyu veya sıcak su \r\n•	Tuz\r\n•	2 yk tereyağı\r\n•	2 yk sıvı yağ\r\n•	1 su bardağı haşlanmış nohut\r\n\r\nNohutlu Pilav Nasıl Yapılır?\r\n\r\n1.	Pirinci yıkayarak, yaklaşık 15-20 dk kadar tuzlu ve ılık suda beklettikten sonra suyunu süzün.\r\n2.	Tencereye sıvı yağı ve tereyağını ekleyin, tereyağı eridikten sonra yıkanıp süzülen pirinçleri ilave edin.\r\n3.	Biraz kavurduktan sonra kaynamış su veya tavuk suyunu, ardından da tuzunu ekleyin.\r\n4.	Haşlanmış nohutları da ilave ederek, tencerenin kapağını kapatın. Dilerseniz haşlanmış nohutları pirinçle birlikte de ekleyebilirsiniz, her iki şekilde de çok güzel oluyor.\r\n5.	Pilavımız kaynayıncaya kadar yüksek, üzeri göz göz olup suyunu çekinceye kadar da kısık ateşte pişirin.\r\n6.	Pilav suyunu çekip pirinçler yumuşadıktan sonra, ocaktan alabilirsiniz.\r\n7.	Üzerini havlu kağıt ile kapattıktan sonra, 10 dakika dinlendirin.', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2019/05/nohutlu-pilav-one-cikan-yeni.jpg', 1),
(36, 'Fırında Sütlaç ', 'Fırında Sütlaç İçin Malzemeler\r\n\r\n•	1 litre süt\r\n•	1 su bardağı şeker\r\n•	Yarım su bardağı pirinç\r\n•	3 yk buğday nişastası\r\n•	1 paket vanilya\r\n•	2 su bardağı su\r\n•	Yarım su bardağı süt (nişastayı açmak için)\r\n\r\nFırında Sütlaç Nasıl Yapılır?\r\n\r\n1.	Fırında sütlaç için öncelikle pirinci haşlayalım. Pirinçleri güzelce yıkadıktan sonra 2 su bardağı su ile pirinçler yumuşayıp pişene kadar haşlayın. Çok az sulu kalacaktır.\r\n2.	Diğer malzemeleri ekleyelim ve sütlacı pişirelim. Haşlanan pirinçlerin üzerine sütü, vanilyayı ilave edip kaynatın.\r\n3.	Bu arada bir kap içerisinde nişasta ve suyu pürüzsüz kıvam alıncaya kadar karıştırın.\r\n4.	Karışım kaynamaya başlayınca şekeri ve yarım su bardağı sütle karıştırdığınız 3 yk buğday nişastasını ilave ediniz. 10-15 dk. daha kaynatıp ocağın altını kapatın.\r\n5.	Sütlaçları fırına sürelim. Fırın için uygun ısıya dayanıklı sütlaç kaselerine sütlaçlarınızı paylaştırın.\r\n6.	Tepsinize soğuk su doldurun ve sütlaç kaplarını fırın tepsinize dizin (Tepsideki su sütlaç kaplarının yarısına kadar gelecek)\r\n7.	Tepsiyi fırınınızın en üst rafına yerleştirin.\r\n8.	180 derecede, sütlaçlarınız kızarana kadar fırınlayın. \r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2015/03/ytk-firin-sutlac-site.jpg', 1),
(37, 'Magnolia ', 'Magnolia İçin Malzemeler\r\n\r\n•	5 su bardağı süt (1 litre)\r\n•	4 yk un\r\n•	100 ml krema (yarım kutu)\r\n•	3/4 (bir yarım+bir çeyrek) su bardağı şeker\r\n•	1 paket vanilya\r\n•	1 adet yumurta\r\n•	1 paket bebe bisküvisi \r\n•	1 su bardağı fındık\r\n•	Çilek\r\n\r\nMagnolia Nasıl Yapılır?\r\n\r\n1.	Magnolianın muhallebisi için uygun bir tencereye süt,  toz şeker, un, yumurta ve  sıvı kremayı alalım.\r\n2.	Malzemelerimizi tel çırpıcıyla karıştırarak pişirmeye başlayalım.\r\n3.	Muhallebi koyulaşıp göz göz oluncaya kadar karıştırarak pişirelim ve ardından ocağı kapatalım.\r\n4.	İçerisine vanilya ilave ederek şöyle bir karıştırdıktan sonra muhallebiyi uygun bir karıştırma kabının içerisine alalım.\r\n5.	Muhallebimiz beklerken üzerini streç filmle kapatalım. Böylelikle üzerinin kabuklanmasını engellemiş oluruz.\r\n6.	Diğer taraftan bebe bisküvisi ve  kavrulmuş fındığı rondoya alalım ve hızlıca rondodan geçirelim.\r\n7.	Soğuyan muhallebiyi mikserle iki dakika kadar çırpalım. Artık tatlıyı sunum yapacağımız kuplara doldurmaya başlayabiliriz. Şimdi kupların tabanına ilk olarak fındıklı bisküvi karışımını yerleştirelim. Sizlerde kaşığın arkasıyla düzeltirseniz çok daha güzel bir görünüm elde edebilirsiniz.\r\n8.	Ardından kuplarımızın kenarlarına dilimlenmiş çilekleri yerleştirelim.\r\n9.	Çilekleri sıraladıktan sonra muhallebiyi kuplara paylaştıralım. Muhallebinin üzerini de yine kaşığın arka tarafı ile düzeltelim.\r\n10.	Son olarak muhallebinin üzerine tekrardan hazırladığımız fındıklı bisküvi karışımından yerleştirelim. Magnoliamızın üzerini dilimlenmiş çilekle süsleyelim.\r\nBu şekilde tatlılarımızı en az 2-3 saat kadar buzdolabında dinlendirdikten sonra çilekli magnolialarımız servise hazır.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2021/06/magnolia-tarifi-yemekcom.jpg', 1),
(38, 'Revani', 'Revani İçin Malzemeler\r\n\r\n•	3 adet yumurta\r\n•	1 çay bardağı toz şeker\r\n•	1 çay bardağı sıvı yağ\r\n•	1 su bardağından biraz eksik süt\r\n•	1,5 su bardağı irmik\r\n•	1 su bardağı un\r\n•	1 paket kabartma tozu\r\n•	1 paket vanilya\r\n•	1 limon kabuğu rendesi\r\n\r\nŞerbeti için;\r\n\r\n•	3 su bardağı toz şeker\r\n•	4 su bardağı su\r\n•	3-4 damla limon suyu\r\n\r\nRevani Nasıl Yapılır?\r\n\r\n1.	İlk olarak şerbeti hazırlayalım. Şeker ve suyu küçük bir tencereye alarak orta ateşte kaynatın.\r\n2.	Kaynamaya başladıktan sonra şerbete limon suyu ilave ederek kısık ateşte yaklaşık 10 dakika kadar daha kaynatıp ocağı kapatın. Şerbeti bir kenara alarak soğumaya bırakın.\r\n3.	Keki hazırlayalım. Uygun bir karıştırma kabına yumurta ve şekeri alarak bol bol çırpın, karışım beyazlayıp köpük köpük olduğunda diğer malzemeleri de ilave ederek kek hamurunu güzelce çırpın.\r\n4.	Hamuru yağlanmış büyük boy borcama dökün.\r\n5.	Önceden 170 derecede ısıttığınız fırında üzeri pembeleşene kadar yaklaşık 35 dakika pişirin.\r\n6.	Fırından aldığımız tatlımız sıcakken soğumuş şerbeti üzerine dökün.\r\n7.	Tatlının şerbetini çekmesi için en az 2-3 saat dinlenmeye bırakın.\r\n8.	Dinlenen tatlımızı dilimleyip, üzerine isteğe göre Hindistan cevizi ya da Antep fıstığı serperek servis edebilirsiniz.\r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2014/06/revani-yemekcom.jpg', 1),
(39, 'Muhallebili Kadayıf Tatlısı ', 'Muhallebili Kadayıf Tatlısı İçin Malzemeler\r\n\r\n•	300-350 g kadar tel kadayıf \r\n•	1,5 su bardağı  dövülmüş ceviz\r\n•	3 yk tereyağı\r\n•	5 yk toz şeker\r\n\r\nMuhallebisi için:\r\n\r\n•	1 litre süt\r\n•	4 yk un\r\n•       3 yk mısır nişastası\r\n•	1 su bardağı toz şeker\r\n•	1 paket vanilya\r\n•	1 adet yumurta sarısı\r\n•	1 paket sıvı krema (200ml)\r\n\r\nMuhallebili Kadayıf Tatlısı Nasıl Yapılır?\r\n\r\n1.	Kadayıfı kavurarak muhallebili kadayıf tatlısının yapımına başlayalım.  Kadayıfı ince ince kırın (kolay kırılması için 2 saat kadar derin dondurucuda bekletebilirsiniz).\r\n2.	Teflon tencereye ya da genişçe bir teflon tavada tereyağını eritin ve şekeri, kadayıfı ekleyerek pembeleşinceye kadar kavurun.\r\n3.	Son olarak cevizi ilave edin ve bir süre daha kavurup ocaktan alın. (Kadayıfları ocaktan aldıktan sonra tencerede bırakırsanız kızarmaya devam edecektir o nedenle ya karıştırmaya devam edin ya da bir kaba alarak soğumasını sağlayın)\r\n4.	Tatlımızın muhallebisini hazırlayalım. Krema ve vanilya hariç tüm malzemeleri tencereye alarak karıştırarak pişirin.\r\n5.	Muhallebi kaynadıktan 3 dakika kadar sonra ocaktan alarak 10-15 dk. soğumaya bırakın.\r\n6.	Daha sonra vanilya ve sıvı kremayı ilave edin ve mikser yardımı ile pürüzsüz bir görüntü alana kadar 4-5 dakika boyunca çırpın.\r\n7.	Hazırladığımız krema ve kadayıfı tepsiye yerleştirelim.  Yaklaşık 30cm çapında bir borcama kızartmış olduğunuz kadayıfların yarısını dökün ve borcamın tabanına güzelce yayın.\r\n8.	Üzerine hazırladığınız kremayı dökün ve en üste kalan kadayıfları serin. Bu işlem için kelepçeli kalıp da kullanabilirsiniz.\r\n9.	Tatlımızı soğumaya bırakalım.  Tatlı oda ısısında ılındıktan sonra buzdolabına kaldırın.\r\n10.	Buzdolabından 3-4 saat kadar dinlendirin.\r\n11.	Dilimledikten sonra servis edebilirsiniz.\r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2014/10/muhallebili-kadayif-tarifi.jpg', 1),
(40, 'Profiterol ', 'Profiterol İçin Malzemeler\r\n\r\n•	 1 su bardağı su\r\n•	 1 su bardağı un\r\n•	 125 gr tereyağı veya margarin\r\n•	 3 adet yumurta \r\n\r\nProfiterol Kreması için;\r\n\r\n•	 2,5 su bardağı süt\r\n•	 3 yk un\r\n•	 1,5 çay bardağı şeker\r\n•	 1 adet yumurta\r\n•	 1 paket vanilya\r\n\r\nÜzeri İçin\r\n\r\n•	 1 paket hazır çikolata sosu ya da benmari usulü eritilmiş 80 gr bitter çikolata\r\n\r\nProfiterol Nasıl Yapılır?\r\n\r\n1.	 İlk olarak profiterolün hamurunu hazırlayalım. Küçük bir tencereye 1 su bardağı suyu ve margarini koyarak kaynatın.\r\n2.	Daha sonra 1 su bardağı unu ekleyerek iyice karıştırın. 2-3 dakika karışımı sürekli karıştırarak pişirin.\r\n3.	Ocağı kapatarak 10-15 dakika hamurun soğumasını bekleyin. Hamur biraz dinlendikten sonra 3 adet yumurtayı hamura yedirmemiz gerekiyor ancak bu noktada önemli bir ayrıntı var. Yumurtaları teker teker hamura kırın ve birini iyice yedirmeden diğer yumurtayı kırmayın. Yumurtaları hamura iyice yedirdikten sonra yapışkan bir hamur elde etmiş olduk. Bu kısım biraz yorucu oluyor ama hamurun kabarması için iyice karıştırmış olmanız gerekiyor. Yumurtaları yedirdikten sonra hamuru 10 dakika dinlendirin.\r\n4.	 Hamurlarımızı pişirelim. Yağlanmış tepsiye, kaşık yardımı ile hamurdan ceviz büyüklüğünde parçalar alarak aralarında 2-3 cm boşluk bulunmasına dikkat ederek resimdeki gibi dökün. Elinizle şekillendirmeye çalışmayın.\r\n5.	Daha önceden 180 derecede ısıttığımız fırına hamuru sürün. üzeri kızarana kadar yaklaşık 40 dakika pişiriyorsunuz.\r\n6.	Profiterol Kremasını hazırlayalım. Hamurlar piştikten sonra kremasını hazırlayın. Vanilya hariç diğer malzemeleri bir tencereye koyarak kremayı pişirin.\r\n7.	Kremayı ocaktan aldıktan sonra vanilyasını ekleyerek karıştırın.\r\n8.	Kremayı profiterol hamurlarına dolduralım. Profiterolün  pişen hamurlarını ikiye bölerek ya da varsa krema sıkma torbası ile içlerini krema ile doldurun ve tepsiye dizin.\r\n9.	Tatlımızın üzerine çikolata sosu gezdirelim. Tüm profiterolleri doldurduktan sonra üzerine çikolata sosunu ya da benmari usulü erittiğiniz çikolatayı gezdirin.\r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2014/11/profiterol-yemekcom2.jpg', 1),
(41, 'İrmik Helvası ', 'İrmik Helvası İçin Malzemeler\r\n\r\n•	3 su bardağı ince irmik\r\n•	2,5 su bardağı şeker\r\n•	350 g tereyağı veya dilerseniz margarin\r\n•	2,5 su bardağı süt\r\n•	2,5 su bardağı su\r\n\r\nİrmik Helvası Nasıl Yapılır?\r\n\r\n1.	İrmik helvası yapmak için ilk olarak küçük bir tencereye şeker ve suyu alarak kaynamaya bırakalım.\r\n2.	Ayrı bir tencereye sütü alarak ayrıca kaynatalım.\r\n3.	Bir tencerede yağı eritelim. Yağımız kızdıktan sonra fıstık kullanacaksanız onları atarak kavurun yoksa  irmiği ekleyerek orta ateşte kavurmaya devam edelim (rengi dönünceye kadar.)\r\n4.	Kavurduğumuz irmiğe şerbeti ardından da sıcak sütü yavaş bir şekilde ilave edelim. Bu aşamada eklediğiniz şerbet sıçrayabilir dikkatli olmanızı öneririm. Tencerenin kapağı yakınınızda olsun ilk sıçramalar geçene kadar kısa bir süre kapağı kapatın. Daha sonra kısık ateşte suyunu iyice çekene kadar karıştıralım. İstediğimiz kıvama gelince karıştırmayı bırakarak ateşten alıp, kapağını kapatıp demlenmeye bırakalım\r\n', 'https://i.lezzet.com.tr/images-xxlarge-recipe/kaymakli_irmik_helvasi-e7128e28-f1ff-4244-8d3e-10e8269d0b18.jpg', 1),
(42, 'Aşure', 'Aşure İçin Malzemeler\r\n\r\n•	1 su bardağı nohut\r\n•	1 su bardağı kuru fasulye\r\n•	3 su bardağı aşurelik buğday\r\n•	1 su bardağı fıstık\r\n•	1 su bardağı fındık içi \r\n•	1.5 su bardağı doğranmış kayısı\r\n•	1 su bardağı kuru üzüm\r\n•	Yarım su bardağı kuş üzümü\r\n•	Yarım su bardağı küp doğranmış portakal kabuğu\r\n•	1 su bardağı küp doğranmış elma\r\n•	4 su bardağı toz şeker\r\n•	1 çorba kaşığı gül suyu\r\n•	Tuz\r\n\r\nAşure Nasıl Yapılır?\r\n\r\n1.	Aşure yapmak için; Bir gece önceden fasulye ve nohut aynı kapta ıslatılır. Bir gece önce buğday yıkanıp sıcak su ile ıslatılır\r\n2.	Ertesi sabah fasulye nohut düdüklü tencerede yumuşayıncaya kadar pişirilir. Buğday da aynı şekilde haşlanır.\r\n3.	Meyveler bir tencerede yumuşayıncaya kadar yaklaşık 10 dk. kaynatılır.\r\n4.	Büyük bir tencereye pişen malzemeler birlikte konulur.\r\n5.	Suyu yetersizse sıcak su eklenir.\r\n6.	Kaynayınca fıstık, fındık, portakal kabuğu, elma, bir çimdik tuz ve şeker atılır. Karıştırılır, 5-10 dk. daha kaynatılıp ocak kapatılır.\r\n7.	Eğer daha koyu kıvamlı olmasını istiyorsanız 2 kaşık buğday nişastasını az suda eritip kaynayınca ilave edebilirsiniz.\r\n8.	Üzerini nar, tarçın, kuş üzümü vs ile süsleyebilirsiniz.\r\n', 'https://cdn.kisikates.com.tr/image-cache/cache/recipe_main_image_large/https---cdn.kisikates.com.tr/recipe-media/663ebc687427435d1e5d084b67c90a8329755636.jpg', 1),
(43, 'Cevizli Tarçınlı Kek ', 'Cevizli Tarçınlı Kek İçin Malzemeler\r\n\r\n•	3 adet yumurta\r\n•	1 su bardağından biraz fazla toz şeker\r\n•	1 çay bardağı sıvı yağ\r\n•	Yarım su bardağı süt\r\n•	1 su bardağı ceviz içi\r\n•	2 çk tarçın\r\n•	1 paket vanilya\r\n•	1 paket kabartma tozu\r\n•	2 su bardağı un\r\n\r\nCevizli Tarçınlı Kek Nasıl Yapılır?\r\n\r\n1.	3 yumurtayı bir kaba kırıp, üzerine bir su bardağından biraz fazla şeker ekleyelim.\r\n2.	Yumurta ve şeker karışımı beyaz oluncaya kadar mikser yardımıyla karıştıralım.\r\n3.	Daha sonra kalan diğer malzemelerimizin tümünü ekleyip yeteri kadar karıştıralım.\r\n4.	Yağladığımız ve hafifçe unladığımız kek kalıbının içine boşaltalım.\r\n5.	Önceden ısıtılmış 160 derecelik fırına koyalım, 45-50 dakika kadar pişirelim.\r\n', 'https://cdn.ye-mek.net/App_UI/Img/out/650/2017/02/tarcinli-cevizli-kek-resimli-yemek-tarifi(15).jpg', 1),
(44, 'Şekerpare', 'Şekerpare İçin Malzemeler\r\n\r\n•	 125 gram oda ısısında margarin\r\n•	 Yarım su bardağı pudra şekeri\r\n•	 3 çorba kaşığı silme irmik\r\n•	 1 adet yumurta\r\n•	 2,5 su bardağı un\r\n•	 1 paket vanilya\r\n•	 1 çk silme kabartma tozu\r\n•	 1 çay bardağı fındık\r\n\r\nŞerbeti için:\r\n\r\n•	 2 su bardağı şeker\r\n•	 3 su bardağı su\r\n•	 4-5 damla limon suyu\r\n\r\nŞekerpare Nasıl Yapılır?\r\n\r\n1.	Karıştırma kabına yağı, pudra şekerini koyup karıştırıyoruz.\r\n2.	Yumurtayı ilave edip tekrar karıştırıyoruz\r\n3.	İrmiği, kabartma tozunu, vanilyayı ve unu azar azar ilave ederek kulak memesi yumuşaklığında hamur elde ediyoruz.\r\n4.	Hamurdan cevizden biraz büyük parçalar kopartıp elimizle yuvarlıyoruz.\r\n5.	Üzerini çok hafif düzleyip ortalarına birer bütün fındık içi yerleştiriyoruz.\r\n6.	Yağlanmış fırın tepsisine diziyoruz.\r\n7.	180 derece önceden ısıtılmış fırında üzeri altın sarısı rengini alana kadar yaklaşık 30 dakika pişiriyoruz.\r\n8.	 Şerbet için derin tencereye suyu ve şekeri koyup yaklaşık 10-15 dakika arası pişiriyoruz.\r\n9.	 İndirmeye yakın limon suyunu ekliyoruz 2-3 dakika daha pişiriyoruz.\r\n10.	Pişen şerbeti ılınmaya bırakıyoruz.\r\n11.	Pişen şekerpareleri fırından alıp 2 dakika kadar bekletip ılık şerbeti üzerine kepçe yardımı ile gezdiriyoruz.\r\n', 'https://image.hurimg.com/i/hurriyet/75/750x422/65649e084e3fe027749270d9.jpg', 1),
(45, 'Kremalı Domatesli Makarna ', 'Kremalı Domatesli Makarna İçin Malzemeler\n•	250 gram makarna\n•	2 domates\n•	Yarım yemek kaşığı domates salçası\n•	1 yemek kaşığı tatlı biber salçası\n•	1 yemek kaşığı zeytinyağı\n•	100 ml sıvı krema\n•	1 tatlı kaşığı tereyağı\n•	1 tatlı kaşığı tuz\n•	1 çay kaşığı karabiber ve pul biber\n•	1 diş sarımsak\n•	2, 5 su bardağı su (200 ml bardak ölçüsü ile)\n•	İsteğe göre kurumuş maydanoz\nKremalı Domatesli Makarna Nasıl Yapılır?\n1.	Kremalı domatesli makarna için öncelikle zeytinyağı, rondodan geçirdiğimiz domatesleri ve salçaları tavamıza alıp, karıştırarak 2-3 dakika kavuralım.\n2.	Kremayı ve tereyağını da ekleyip, tereyağı eriyene kadar karıştıralım.\n3.	Makarnayı da ekleyerek tekrar karıştıralım ve suyumuzu ekleyelim.\n4.	Suyumuz kaynadıktan sonra sarımsak ve baharatları ekleyelim, karıştıralım.\n5.	Ocağımızı orta ateşe alıp kapağı kapalı bir şekilde suyu çekene kadar pişirelim. Pişme süresi değişiklik gösterebilir, bu aşamada kontrollü olmalısınız.\n6.	İsterseniz piştikten sonra taze veya kuru maydanoz ekleyip karıştırabilirsiniz. \n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2022/04/soslu-makarna-tarifi-yemekcom.jpg', 1),
(46, 'Kısır', 'Kısır İçin Malzemeler\r\n\r\n•	1 büyük su bardağı ince bulgur\r\n•	Yarım su sıcak su (bulguru ıslatmak için)\r\n•	3 yaprak marul\r\n•	1 demet maydanoz\r\n•	3 adet taze soğan\r\n•	1 yk zeytinyağı (soğanı kavurmak için)\r\n•	1 küçük salatalık\r\n•	5 tane çeri domates\r\n•	1 tane orta boy sivri biber\r\n•	Yarım çay bardağı zeytinyağı (az gelirse ekleme yapın)\r\n•	1 yk nar ekşisi\r\n•	Karabiber, pul biber, kimyon, tuz\r\n•	1 yk biber salçası, 1 tk domates salçası\r\n•	1 diş sarımsak\r\n•	1 küçük soğan\r\n\r\nKısır Nasıl Yapılır?\r\n\r\n1.	Öncelikle bulguru sıcak suyla bir miktar ıslatıyoruz.\r\n2.	Ama çok az su ile, sadece suyu döktüğümüz anda hemen kendisini çekecek kadar ve kapağını kapatıp 5 dakika demlendiriyoruz.\r\n3.	Küçük bir tavada kuru soğanı ve sarımsağı, 1 yk zeytinyağı ile çok az kavurup salçasını ilave ediyoruz.\r\n4.	2 dakika daha kavurup ocağı kapatıyoruz.\r\n5.	Bulgurun içine döküyoruz ve bütün baharatları, nar ekşisini ve 1 çay bardağı zeytinyağını da ilave edip iyice harmanlıyoruz.\r\n6.	İnce ince doğradığımız yeşillikleri ilave edip iyice birbirine yedirdikten sonra en son domateslerimizi ilave edip karıştırıyoruz ve servis yapıyoruz.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2023/05/yogurma-kisir-sunum-yemekcom.jpg', 1),
(47, 'Kabak Mücveri ', 'Kabak Mücveri İçin Malzemeler\r\n\r\n•	 3 adet yumurta\r\n•	 3 adet kabak\r\n•	 Yarım su bardağı un\r\n•	 2-3 dal yeşil soğan\r\n•	 Yarım demet maydanoz\r\n•	 Bir tutam dereotu\r\n•	 Tuz, karabiber, pul biber\r\n\r\nKabak Mücveri Nasıl Yapılır?\r\n\r\n1.	İlk olarak mücver malzemelerini hazırlayalım. Kabakları soyarak rendenin iri kısmında rendeleyelim.\r\n2.	Yeşil soğan, maydanoz ve dereotunu minik minik doğrayalım.\r\n3.	Kabak Mücver harcını hazırlayalım. Yumurtaları derince bir kaba alalım.\r\n4.	Üzerine un, pul biber, karabiber ve tuzu ilave edilerek pürüzsüz kıvam alana kadar çırpalım.\r\n5.	Ardından suyunu iyice sıktığımız kabakları ve doğranmış dereotu, yeşil soğan ve maydanozu eklenerek karıştıralım. Mücver harcımız hazır.\r\n6.	 Mücveri tavada pişirelim. Teflon tavaya az miktarda sıvı yağ alalım.\r\n7.	Isınan yağımıza kabak karışımından bir kaşık dökelim, çevirerek kızartalım.\r\n8.	Mücverlerin her iki yüzü de kızardıktan sonra havlu kağıt serilmiş tabağa alalım.\r\n', 'https://cdn.yemek.com/mnresize/940/940/uploads/2014/07/mucver-ytk-site.jpg', 1),
(48, 'Fırında Karnabahar ', 'Fırında Karnabahar İçin Malzemeler\r\n\r\n•	1 küçük boy karnabahar\r\n•	1 su bardağı yoğurt\r\n•	2 adet yumurta\r\n•	Yarım çay bardağı sıvıyağ\r\n•	1 yk un\r\n•	Kaşar peynir rendesi\r\n•	Tuz, pul biber\r\n\r\nFırında Karnabahar Nasıl Yapılır?\r\n \r\n1.	Karnabaharlar çiçek çiçek koparılarak tuzlu suda haşlanır.\r\n2.	Derince bir kapta kaşar peyniri hariç tüm malzeme karıştırılır.\r\n3.	Haşlanan karnabaharlar hazırlanmış olan sosa batırılıp yağlanmış borcama dizilir.\r\n4.	Üzerine 1-2 parça katı yağ koyup (ben yağ kullanmadım) 200 derecede 20 dakika kadar fırında pişirilir.\r\n5.	Daha sonra kaşarlar eklenerek tekrar fırına sürülür.\r\n6.	Kaşarlar eriyip kızarana kadar pişirilir. \r\n', 'https://cdn.ye-mek.net/App_UI/Img/out/650/2021/12/firinda-sutlu-karnabahar-resimli-yemek-tarifi(11).jpg', 1),
(49, 'Ispanak Yemeği ', 'Ispanak Yemeği İçin Malzemeler\r\n\r\n•	1 kg ıspanak\r\n•	1 adet kuru soğan\r\n•	Yarım çay bardağı pirinç\r\n•	2 yk sıvı yağ\r\n•	1 yk domates salçası\r\n•	Tuz, karabiber, pul biber\r\n\r\nIspanak Yemeği Nasıl Yapılır?\r\n\r\n1.	Başlangıç olarak ıspanakları temizleyelim.\r\n2.	Diğer taraftan soğanı  doğrayıp sıvı yağda pembeleşenedek kavuralım.\r\n3.	Salçayı ilave edelim.\r\n4.	Ardından ıspanakları da ekleyelim ve ıspanaklar eriyinceye kadar kavuralım.\r\n5.	Yarım çay bardağı yıkanmış pirinci, tuz ve baharatları da ilave edelim.\r\n6.	1 su bardağı kaynar suyu da ekleyerek tencerenin kapağını kapatalım, kısık ateşte pirinçler yumuşayana dek pişirelim.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2023/11/ispanak-yemegi-yemekcom.jpg', 1),
(50, 'Pırasa Yemeği ', 'Pırasa Yemeği İçin Malzemeler\r\n\r\n•	5-6 dal pırasa (beyaz kısımları kullanılacak)\r\n•	2 adet havuç\r\n•	1 yk domates salçası\r\n•	5-6 yk domates sosu\r\n•	Yarım Türk kahvesi fincanı pirinç\r\n•	2 yk sıvı yağ\r\n•	Tuz\r\n•	Sıcak su\r\n\r\nPırasa Yemeği Nasıl Yapılır?\r\n\r\n1.	Pırasa yemeği yapmak için pırasalar temizlenerek 1 cm uzunluğunda doğranır.\r\n2.	Bol su ile yıkanarak suyunun süzülmesi sağlanır.\r\n3.	2 adet orta boy havucun dış kısmı soyulur ve ince ince halka şeklinde dilimlenir.\r\n4.	Tencereye sıvı yağ alınarak salça eklenir ve kavrulur.\r\n5.	Rendelenmiş  domates  eklenerek 1-2 tur çevirelim.\r\n6.	Daha sonra havuç ilave edilir ve 2-3 dk hep birlikte kavrulması sağlanır.\r\n7.	Suyu süzülen pırasalar ilave edildikten sonra karıştırılır ve tencerenin kapağı kapatılır.\r\n8.	Orta ateşte pırasalar suyunu salıp, suyunu çekene kadar bu şekilde pişirilir.\r\n9.	Son olarak yıkanmış pirinç ilave edilir, tuzu ayarlanır ve yemekle aynı hizaya gelecek kadar sıcak su eklenir. Su miktarı gerekirse eğer sonradan ilave ederek ayarlayabilirsiniz.\r\n10.	Tencerenin kapağı kapatılarak havuçlar ve pırasalar pişene kadar kısık ateşte pişirilir. Tüm sebzeler yumuşadıktan sonra yemeğimiz servise hazır.\r\n', 'https://cdn.yemek.com/mncrop/940/625/uploads/2018/11/pirincli-pirasa-guncelleme-sunum-1.jpg', 1),
(51, 'Kuru Fasulye', 'Kuru Fasulye İçin Malzemeler\r\n•	2 su bardağı kuru fasulye\r\n•	300 gr dana kuşbaşı et\r\n•	1 tane kuru soğan\r\n•	1 tane sivri biber\r\n•	1 yk domates salçası, 1 tk acı biber salçası\r\n•	Tuz\r\n•	4, 5 -5 bardak sıcak su\r\n•	Çok az sıvı yağ\r\n•	1 tane küp şeker\r\nKuru Fasulye Nasıl Yapılır?\r\n1.	Kuru fasulyeyi akşamdan soğuk suyla ıslatıyoruz, ertesi gün suyunu süzüp bolca yıkıyoruz.\r\n2.	Diğer taraftan etleri biraz sıvı yağ eklediğimiz düdüklü tencerenin içine alıyoruz ve harlı ateşte rengi dönene kadar kavuruyoruz.\r\n3.	Kavrulduğunda kuru fasulyeyi içine ekliyoruz.\r\n4.	Üzerine soğan ve biberi de doğrayıp salçaları da ekliyoruz ve karıştırıyoruz.\r\n5.	Suyunu da fasulyelerin üzerini biraz geçecek kadar yaklaşık 4,5 -5 bardak kadar sıcak suyu ekliyoruz.\r\n6.	Tuzunu ve şekerini de atıp karıştırıp kapağını kapatıyoruz.\r\n7.	Harlı ateşte düdük ötene kadar daha sonra ise düdüğünü indirip orta ateşte 30 dk. kadar pişiriyoruz.\r\n8.	Pişme süresi fasulyenin tazeliğine bağlı değişebilir.\r\n9.	30 dakikadan sonra bir kontrol etmekte fayda var. Pişmemişse yeniden biraz daha kaynatabilirsiniz.\r\n', 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/00b537a0370767a1962c742c1ad69d7e/Derivates/b68c6068b48575089df64873493edf070924766d.jpg', 1),
(52, 'Etsiz Bamya ', 'Etsiz Bamya İçin Malzemeler\r\n\r\n•	Yarım kg taze bamya\r\n•	2 adet domates\r\n•	1 adet soğan\r\n•	3 adet yeşil biber\r\n•	Yarım yk salça\r\n•	2 yk sıvı yağ\r\n•	Yarım limon\r\n•	Karabiber, pul biber, tuz\r\n•	5 su bardağı sıcak su\r\n\r\nEtsiz Bamya Nasıl Yapılır?\r\n\r\n1.	Soğanı yemeklik doğrayarak kavurun.\r\n2.	Pembeleşince doğranmış biberi ilave ederek biberleri de kavurun.\r\n3.	Küp küp doğranmış domates ve salçayı ilave edin.\r\n4.	2-3 dk. karıştırın ve yıkanmış temizlenmiş bamyaları ekleyin.\r\n5.	1-2 dakika da bamyalar kavrulunca yarım limon suyunu sıkın ve sıcak su ilave edin.\r\n6.	Son olarak tuz ve baharatları ekleyerek çok karıştırmadan pişmeye bırakın.\r\n', 'https://i.lezzet.com.tr/images-xxlarge-recipe/etli-bamya-yemegi-5060e35a-3a93-496b-8fd7-df055cbea094.jpg', 1),
(53, 'Kahvaltılık Krep ', 'Kahvaltılık Krep İçin Malzemeler\r\n\r\n•	2 adet yumurta\r\n•	2 su bardağından biraz az un\r\n•	2 su bardağı süt \r\n•	1 çk tuz\r\n•	Pişirmek için tereyağı veya sıvı yağ\r\n\r\nKahvaltılık Krep Nasıl Yapılır?\r\n\r\n1.	Krep tarifi hazırlamak için un, süt ve suyu karıştırma kabına alarak hiç topak kalmayana kadar iyice çırpın.\r\n2.	Yumurtaları ekleyin biraz daha çırpın. Kek hamurundan daha akıcı bir kıvamda hamur edin.\r\n3.	Teflon tavaya 1 çk kadar tereyağı veya sıvı yağ koyup fırça ile yayın.\r\n4.	Kızgın tavaya 1 kepçe krep hamuru dökün, sağa sola eğerek yayın.\r\n5.	Her iki tarafını çevirerek hafif kızarana kadar orta ateşte pişirin. Tüm harcınız bitene kadar bu işleme devam edin. \r\n', 'https://image.hurimg.com/i/hurriyet/75/0x0/5c10b7430f254418d86cee28.jpg', 1),
(54, 'Pastane Poğaçası ', 'Pastane Poğaçası İçin Malzemeler\r\n\r\n•	1 paket oda sıcaklığında margarin ya da tereyağı (250 g)\r\n•	1 yk instant maya\r\n•	1 çay bardağı süt \r\n•	1 tk tuz\r\n•	1 çay bardağı sıvı yağ\r\n•	2 adet yumurta (birinin sarısı üstüne)\r\n•	2 yk şeker\r\n•	6 su bardağı un\r\n\r\nİçi için;\r\n•	Peynir\r\n\r\nÜzeri için;\r\n•	1 adet yumurta sarısı\r\n\r\nPastane Poğaçası Tarifi Nasıl Yapılır?\r\n\r\n1.	Hamuru için uygun bir yoğurma kabına ılık süt, sıvı yağ, yumurta, şeker, tuz ve mayayı alarak karıştıralım.\r\n2.	Daha sonra oda sıcaklığındaki tereyağını ekleyim.\r\n3.	Unu da yavaş yavaş kontrollü bir şekilde ekleyerek hamurumuzu yoğurmaya başlayalım. Ele yapışmayan bir hamur elde etmemiz gerekiyor.\r\n4.	Hazır olan hamurumuzdan avuç içi büyüklüğünde bezeler kopartalım ve parmaklarımızın ucu ile genişletelim.\r\n5.	Hamurumuzun ortasına peynirli iç harcından yerleştirelim. İç harcı için lor peyniri, kaşar peyniri, beyaz peynir ya da hepsini karıştırarak da kullanabilirsiniz.\r\n6.	İç harcını yerleştirdikten sonra iki ucunu kapatarak birleştirelim ve tepsimize yerleştirelim. Tüm hamur bitinceye kadar bu işleme devam edelim.\r\n7.	Son olarak poğaçalarımızın üzerine yumurta sarısı sürelim ve çatalla bastırarak çizgiler oluşturalım.\r\n8.	Hazır olan poğaçalarımızı önceden ısıtılmış 200°C fırında yaklaşık 20-25 dakika pişmeye bırakalım.\r\n', 'https://i.ytimg.com/vi/Wtu0mFhMybo/maxresdefault.jpg', 1);
INSERT INTO `yemektarifi` (`Id`, `Baslik`, `Aciklama`, `ResimUrl`, `KullaniciId`) VALUES
(55, 'Kolay Pankek', 'Kolay Pankek İçin Malzemeler\r\n•	2 adet yumurta\r\n•	2 yk şeker\r\n•	1 su bardağı süt\r\n•	1,5 su bardağı un\r\n•	1 paket kabartma tozu\r\n•	1 paket vanilya\r\nPişirme aşamasında kullanmak için;\r\n•	sıvı yağ\r\n\r\nServis önerisi:\r\n•	Kivi, muz, çilek, reçel, bal, çikolata\r\nKolay Pankek Nasıl Yapılır?\r\n1.	Pankek yapmak için öncelikle yumurtalar ve şekeri uygun bir karıştırma kabına alarak iyice çırpalım.\r\n2.	Süt, un, kabartma tozu, vanilya ilave çırpma teli ile çırpalım. Siz dilerseniz mikser ile de çırpabilirsiniz. Kek kıvamından biraz daha koyu olacak şekilde hamur hazırlayalım.\r\n3.	Teflon ya da yapışmaz bir tavaya az sıvı yağı dökelim, fırça yardımı ile her tarafına dağıtalım. Sıvı yağı az kullanmak pankek yapmanın püf noktalarındandır. Dilerseniz peçete ile de tavaya dağıtabilirsiniz.\r\n4.	1 büyük kaşık hamur dökülerek hamurun kendi kendine yayılmasını bekleyelim.\r\n5.	Üzeri göz göz olmaya başlayan pankeklerimizi spatula yardımı ile ters çevirelim. Diğer taraflarını da pişirelim.\r\n6.	Her iki tarafı da pişen pankeklerimizi servis tabağına alalım.\r\n7.	Üzerine  pudra şekeri serpilerek zevkinize göre muz, kivi, çilek, çikolata, bal, sürülebilir çikolata, reçel ile servis edebilirsiniz.\r\n', 'https://yuvamaya.com.tr/upload/recipes/eksi-mayali-pankek.jpg', 1),
(56, 'Dereotlu Poğaça', 'Dereotlu Poğaça Tarifi İçin Malzemeler\r\nHamuru için;\r\n\r\n•	1 çay bardağı sıvı yağ\r\n•	1 çay bardağı yoğurt\r\n•	1 paket kabartma tozu\r\n•	1 çk tuz\r\n•	 Yarım demet ince kıyılmış dereotu\r\n•	 1 adet yumurta\r\n•	 Aldığı kadar un (yaklaşık 2.5-3 su bardağı)\r\n\r\nÜzeri için;\r\n•	1 yumurta sarısı\r\n\r\nDereotlu Poğaça Tarifi Nasıl Yapılır?\r\n\r\n1.	İlk olarak poğaçamızın hamurunuz hazırlayalım. Bir kabın içine malzemelerin tamamını koyup yoğurarak yumuşak bir hamur elde edelim.\r\n2.	Unu yavaş yavaş ekleyerek hamurun sertliğini ayarlayalım. Unu kontrollü ilave etmenizi tavsiye ederiz. Hamurunuzun kıvamı sert olursa poğaçalarınız da sert olabilir.\r\n3.	Poğaçalarımızı şekillendirelim. Fotoğrafta görüldüğü gibi hamuru iyice yoğurduktan sonra minik bezeler yapıp yağlı kağıt serdiğimiz fırın tepsisine yerleştirelim.\r\n4.	Verilen ölçülere göre yaklaşık 11 tane poğaça elde edebilirsiniz. Eğer poğaçalarınızı daha küçük yaparsanız 15-16 adet poğaça elde edebilirsiniz. Fırına sürmeden önce bir süre hamuru dinlendirmenizi öneririm.\r\n5.	Poğaçalarımızı fırına sürelim. Üzerlerine yumurta sarısı sürüp, 180 derece ısıtılmış fırında üzeri kızarıncaya kadar pişirin.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2020/03/dereotlu-pogaca-yemekcom-1.jpg', 1),
(57, 'Evde Ekmek Yapımı ', 'Evde Ekmek Yapımı İçin Malzemeler\r\n\r\n•	2 yk kuru maya\r\n•	1 yk toz şeker\r\n•	1,5-2 su bardağı ılık su \r\n•	4 su bardağı un \r\n•	2 tk tuz \r\n\r\nÜzeri için;\r\n•	Yoğurt\r\n\r\nEvde Ekmek Nasıl Yapılır?\r\n\r\n1.	İlk olarak mayanın çözünmesi için uygun bir kabın içerisine aldığımız ılık suya, kuru maya ve şekeri ekleyerek karıştıralım. Normal maya kullanacaksanız 8-10 dakika arası mayanın aktifleşmesi için bekletirseniz yeterli.\r\n2.	Yoğurma kabının içerisine unu alalım, üzerine tuzu ekleyerek ortasını havuz şeklinde açalım.\r\n3.	Çözdürdüğümüz mayayı hazırladığımız çukura boşaltalım ve hamurumuzu yoğurmaya başlayalım.\r\n4.	Hamur yumuşak olduğu için elinize yapışabilir. Bu durumda elinizi ıslatarak hamuru daha kolay bir şekilde toparlayabilirsiniz.\r\n5.	Daha sonra hamurun üzerini kapatalım ve üzerini bir bez ile sararak 40 dakika kadar sıcak bir ortamda mayalanmaya bırakalım.\r\n6.	Daha sonra hamurumuzu un serptiğimiz tezgaha alalım ve elimizle yoğurarak toparlayalım.\r\n7.	Toparladığımız hamurumuzu ucunu ıslattığımız bıçak ile 8 eşit parçaya ayıralım.\r\n8.	Böldüğümüz hamurları bezeler haline getirelim, elimize ve tezgaha yapışmaması için bol bol unlayalım.\r\n9.	Bezeleri elimizle yuvarlayalım ve kenarları daha ince olacak şekilde rulo haline getirelim.  Ekmeklerinize benim gibi şekil vermek yerine rulo yapmadan daire şeklinde de pişirebilirsiniz.\r\n10.	Şekillendirdiğimiz hamurları pişirme kağıdı serdiğimiz fırın tepsisine alalım, üzerine nemli bir bez örterek tepsi mayasının gelmesi için 15-20 dakika bekletelim. Eğer üzerini nemli bir bez ile örtmezseniz hamurların üzeri kuruyup çatlayacaktır.\r\n11.	Tepsi mayası gelen hamurlarımızın üzerlerini açalım, çırptığımız yoğurdu fırça yardımı ile tüm hamurlarımızın üzerine sürelim. Bu sayede ekmeklerin üzeri nar gibi kızaracaktır.\r\n12.	Son olarak keskin bir bıçak yardımı ile ekmeklerimizin üzerine kesikler atalım sonrasında önceden 230°C de ısıttığımız fırında yaklaşık 20-25 dakika pişmeye bırakalım. \r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2020/03/somun-ekmek-yeni-one-cikan.jpg', 1),
(58, 'Mantı ', 'Mantı İçin Malzemeler\r\n\r\n•	3 su bardağı un\r\n•	1 su bardağı ılık su\r\n•	Tuz\r\n•	1 adet yumurta\r\n\r\nİçi için:\r\n•	250 g az yağlı kıyma\r\n•	1 adet orta boy soğan\r\n•	Karabiber, tuz, pul biber\r\n\r\nPişirmek için:\r\n•	Tereyağı\r\n•	2 yk salça\r\n\r\nÜzeri için:\r\n•	Sarımsaklı Yoğurt\r\n•	Nane, sumak, pul biber\r\n\r\nMantı Nasıl Yapılır?\r\n\r\n1.	Genişçe bir kapta unun ortasını açın, yumurtayı kırın, bir tutam tuz serpin ve azar azar su ilave ederek hamuru yoğurun.\r\n2.	Hamurun ne çok kaskatı ne de çok yumuşak olmalıdır.\r\n3.	Hamurdan bezeler yaparak, bunları teker teker, hazır yufkadan daha kalınca olarak açın.\r\n4.	Diğer taraftan kıymanı içine kırmızıbiber, karabiber, tuz ve rendelemiş olduğunuz soğanı ekleyerek biraz yoğurun.\r\n5.	Kıymadan kopardığınız küçük parçaları kare kare kesmiş olduğunuz hamurun üzerine koyun.\r\n6.	Hamurların 4 köşesini bir araya getirip şekillendirin.\r\n7.	Mantılar hazır olunca kaynayan suya atarak 15-20dk kadar pişirin.\r\n8.	Bu arada küçük bir tavada tereyağını eriyip salçayı kavurun.\r\n9.	Pişmekte olan mantının suyuna ilave edin.\r\n10.	5 dk kadar daha pişirdikten sonra ocaktan alın.\r\n11.	Mantıyı tabaklara koyun üzerine sarımsaklı yoğurt dökün.\r\n12.	Nane ve bol sumak serperek servis edebilirsiniz.\r\n', 'https://www.shopsa.com.tr/upload/news/960x600/mant.jpg', 1),
(59, 'Patatesli Çıtır Börek ', 'Patatesli Çıtır Börek İçin Malzemeler\r\n\r\n•	4 adet yufka\r\n•	1 su bardağı sıvı yağ\r\n•	1 yk sirke\r\n•	3 yk un\r\n\r\nİç harcı için:\r\n•	4 adet orta boy patates\r\n•	2 yk sıvı yağ\r\n•	1 adet soğan\r\n•	1 tk nane, 1 çk kırmızı toz biber, 1 çk pul biber, 1 çk karabiber, tuz\r\n\r\nÜzeri için:\r\n•	1 adet yumurta\r\n\r\nPatatesli Çıtır Börek Nasıl Yapılır?\r\n\r\n1.	Patatesleri haşlayın, kabuklarını soyarak küçük küçük doğrayın.\r\n2.	Rendelediğiniz ya da küçük doğradığınız soğanı sıvı yağda kavurduktan sonra patatesleri ilave edin ve nane, tuz, kırmızı toz biberi de ekleyerek kavurun.\r\n3.	İç harcını soğumaya bırakın.\r\n4.	Sıvı yağ, sirke ve unu iyice çırparak boza kıvamında sos hazırlayın.\r\n5.	Yufkalardan bir tanesini serin ve yarısının üzerine hazırladığınız sostan 3-4 yk dökerek fırça ile yayın.\r\n6.	Yufkanın diğer yarısını soslu kısmın üzerine kapatın ve üzerini tekrar sos ile ıslatın.\r\n7.	2 katlı yufkanızı pizza dilimi şeklinde 6 parça kesiyorsunuz ve üçgenlerin kalın kısımlarına iç harcından koyarak sigara böreği sarar gibi sarıyorsunuz.\r\n8.	Tüm malzemeleri aynı şekilde yaptıktan sonra pişirme kağıdı serili fırın tepsisine alalım, üzerine yumurta sarısı sürüp susam serperek 180 derece ısıttığınız fırında patatesli börekler kızarana kadar pişiriyorsunuz.\r\n', 'https://cdn.yemek.com/mnresize/1250/833/uploads/2022/05/patatesli-citir-borek-tarifi-yemekcom.jpg', 1);

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `kullanici`
--
ALTER TABLE `kullanici`
  ADD PRIMARY KEY (`Id`);

--
-- Tablo için indeksler `yemektarifi`
--
ALTER TABLE `yemektarifi`
  ADD PRIMARY KEY (`Id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `kullanici`
--
ALTER TABLE `kullanici`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- Tablo için AUTO_INCREMENT değeri `yemektarifi`
--
ALTER TABLE `yemektarifi`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=65;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
